<?php

/**
 * @file
 * Contains import_json.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function import_json_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the import_json module.
    case 'help.page.import_json':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Import JSON') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function import_json_theme() {
  return [
    'import_json' => [
      'render element' => 'children',
    ],
  ];
}
